# Generated by Django 4.2.9 on 2024-02-03 15:11

from django.db import migrations
import json
from pathlib import Path
from django.contrib.gis.geos import fromstr

DATA_FILENAME = 'export.json'

def load_data(apps, schema_editor):
    Venue = apps.get_model('nerbyvenues', 'Venue')
    json_file = Path(__file__).parents[2] / DATA_FILENAME
    print(json_file)
    with open(json_file, encoding='utf-8') as datafile:
        items = json.load(datafile) 
        for item in items['elements']:
            try:
                itemType = item['type']
                if itemType == 'node':
                    tag = item['tags']
                    name = tag.get('name', 'no-name')
                    longitude = item.get('lon', 0)
                    latitude = item.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid = 4326)
                    Venue(name = name, location = location).save()
            except KeyError:
                pass



class Migration(migrations.Migration):

    dependencies = [
        ('nerbyvenues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
